App\Business\User\UserRegistrationAction:
  properties:
    username:
      - NotBlank: ~
      - Length:
          min: 8,
          max: 50,
          minMessage: "Le nom d'utilisateur doit faire 8 charactère minimum."
          maxMessage: "Votre nom d'utilisateur est trop long"
      - Type: string
    email:
      - NotBlank: ~
      - Email:
          message: "Adresse mail non valide."
    password:
      - NotBlank: ~
      - Length:
          min: 8,
          minMessage: "Votre mot de passe est trop court"

    passwordConfirmation:
      - NotBlank: ~
      - EqualTo:
          propertyPath: password
          message: "Mot de passe différent du premier"




